name: Build

on:
    push:
        branches:
            - 'main'
            - 'renovate/*'
        tags:
            - 'v*' # For v1.0, v0.1.0, etc
    pull_request:
        branches:
            - 'main'
    schedule:
        -   cron: '0 0 * * *'
    workflow_dispatch:

concurrency:
    group: ${{ format('{0}-{1}', github.job, github.ref) }}
    cancel-in-progress: true

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ ubuntu-latest, macos-latest, windows-latest ]

        steps:
            -   name: Checkout code
                uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

            -   name: Create out directory
                run: mkdir -p out

            -   name: Make
                run: make

            -   name: Upload Build Results
                uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4
                with:
                    name: Build Results (on ${{ matrix.os }})
                    path: ${{ github.workspace }}/out/
